# Generated by Django 5.1.4 on 2025-09-21 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='autenticationuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='autenticationuser',
            name='username',
        ),
    ]
