# Generated by Django 5.1.4 on 2025-09-21 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical', '0002_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='allergies',
            field=models.ManyToManyField(blank=True, to='medical.allergy', verbose_name='Alergias'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='child',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_medico', to='patients.child'),
        ),
    ]
