# Generated by Django 5.1.6 on 2025-02-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_child_parent_alter_employee_role_medicalhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autenticationuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='autenticationuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
